export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CHANGE_USER_LOGGED_IN = 'CHANGE_USER_LOGGED_IN';

export const UPDATE_INFO_REQUEST = 'UPDATE_INFO_REQUEST';
export const UPDATE_INFO_SUCCESS = 'UPDATE_INFO_SUCCESS';
export const UPDATE_INFO_FAILURE = 'UPDATE_INFO_FAILURE';

export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAILURE = 'GET_INFO_FAILURE';

export const GET_ROOMS_LIST_REQUEST = 'GET_ROOMS_LIST_REQUEST';
export const GET_ROOMS_LIST_SUCCESS = 'GET_ROOMS_LIST_SUCCESS';
export const GET_ROOMS_LIST_FAILURE = 'GET_ROOMS_LIST_FAILURE';

export const GET_ROOM_USERS_LIST_REQUEST = 'GET_ROOM_USERS_LIST_REQUEST';
export const GET_ROOM_USERS_LIST_SUCCESS = 'GET_ROOM_USERS_LIST_SUCCESS';
export const GET_ROOM_USERS_LIST_FAILURE = 'GET_ROOM_USERS_LIST_FAILURE';

export const APPLY_MEMBERSHIP_REQUEST = 'APPLY_MEMBERSHIP_REQUEST';
export const APPLY_MEMBERSHIP_SUCCESS = 'APPLY_MEMBERSHIP_SUCCESS';
export const APPLY_MEMBERSHIP_FAILURE = 'APPLY_MEMBERSHIP_FAILURE';

export const GET_DEMANDS_REQUEST = 'GET_DEMANDS_REQUEST';
export const GET_DEMANDS_SUCCESS = 'GET_DEMANDS_SUCCESS';
export const GET_DEMANDS_FAILURE = 'GET_DEMANDS_FAILURE';

export const ANSWER_DEMAND_REQUEST = 'ANSWER_DEMAND_REQUEST';
export const ANSWER_DEMAND_SUCCESS = 'ANSWER_DEMAND_SUCCESS';
export const ANSWER_DEMAND_FAILURE = 'ANSWER_DEMAND_FAILURE';

export const GET_LOG_MESSAGES_REQUEST = 'GET_LOG_MESSAGES_REQUEST';
export const GET_LOG_MESSAGES_SUCCESS = 'GET_LOG_MESSAGES_SUCCESS';
export const GET_LOG_MESSAGES_FAILURE = 'GET_DEMANDS_FAILURE';
