export const RELIGIOUS_BELIEF_TYPES = {
  NONE: -1,
  RELIGIOUS: 1,
  NON_RELIGIOUS: 2,
  NEITHER: 3,
};

export const SLEEP_STATUS_TYPES = {
  NONE: -1,
  LIGHT_SENSITIVE: 1,
  NOISE_SENSITIVE: 2,
  BOTH: 3,
  NEITHER: 4,
};

export const CLEAN_STATUS_TYPES = {
  NONE: -1,
  SENSITIVE: 1,
  NOT_IMPORTANT: 2,
};

export const NOISE_STATUS_TYPES = {
  NONE: -1,
  SENSITIVE: 1,
  NOT_IMPORTANT: 2,
};

export const PERSONALITY_STATUS_TYPES = {
  NONE: -1,
  INTROVERT: 1,
  EXTROVERT: 2,
};
